name: "Run performance tests"
on:
  push:
    branches: [main]
  pull_request:
    branches: ['**']

jobs:
  main:
    name: Run performance tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'
          
      - name: Run Reassure
        run: ./reassure-tests.sh

      - name: Run Danger.js
        run: yarn danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}